# Generated by Django 3.2.7 on 2021-10-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='emotion',
            field=models.CharField(choices=[('happy', 'Happy')], default='Happy', max_length=10),
        ),
    ]
