# Generated by Django 3.2.7 on 2021-10-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_song_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('gujarati', 'Gujarati'), ('marathi', 'Marathi')], default='Hindi', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='emotion',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('angry', 'Angry')], default='Happy', max_length=10),
        ),
    ]
