# Generated by Django 3.2.7 on 2021-11-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211007_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='profile_pics\\download.jpg', upload_to='songs_images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='emotion',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('angry', 'Angry')], default='happy', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('gujarati', 'Gujarati'), ('marathi', 'Marathi')], default='hindi', max_length=10),
        ),
    ]
